INSERT INTO LOCATION (ID, NAME, DESCRIPTION, IMAGE_URL, SEASON_ID, REGION_ID)
VALUES (1,
        'Gergeti Trinity Church',
        'Unquestionably one of Georgia’s most recognizable monuments, the Gergeti Trinity Church is sure to have crossed your Instagram page in the past. Soaring high above the clouds against a backdrop of towering mountains, this picturesque 14th century church is a must see on any Georgian adventure.',
        'https://storage.georgia.travel/images/gergeti-church-in-kazbegi.webp',
        1,
        2),
       (2,
        'Truso Valley',
        'Despite its relatively small size, Georgia is a country of immense diversity, with uniquely beautiful places scattered across the countryside just waiting to be discovered. One such place is the breathtaking Truso Valley.',
        'https://storage.georgia.travel/images/trusso-valley-gnta.webp',
        2,
        2),
       (3,
        'Gomismta',
        'Gomismta (Gomi Mountain) is a climatic resort that occupies one of the most prominent places on the list of resorts in the Guria Region. It is 33 km from Ozurgeti city, at 2,100-2,755 meters above sea level. Gomismta is also called the "Resort in Clouds".',
        'https://storage.georgia.travel/images/gomi-mountain-gnta.webp',
        2,
        1),
       (4,
        'Abudelauri Lakes',
        'The colourful lakes of Abudelauri are one of the most visually appealing natural sights of Georgia. This is also a wonderful hiking destination, so if you''re traveling to Georgia in summer, consider adding this wild piece of paradise to your must-visit list.',
        'https://storage.georgia.travel/images/abudelauri-lakes.webp',
        0,
        2),
       (5,
        'Prometheus Cave',
        'Georgia is a country of beautiful landscapes and amazing nature, but there is a sight which truly stands apart from other natural monuments – an underground cave lit with colourful lights, whose waterfalls, lakes, stone curtains, helictites, needle-like anthodites, and other unique formations you will never forget. This is Prometheus Cave, visited by more than 200,000 people every year.',
        'https://storage.georgia.travel/images/caving-in-prometheus-cave-1.webp',
        0,
        0),
       (6,
        'Okatse Canyon',
        'Imereti region is famous for its lush greenery, dramatic limestone cliffs and plentitude of water - rivers, streams and lakes. Okatse Canyon is a perfect example of this.',
        'https://storage.georgia.travel/images/okatse-canyon-gnta.webp',
        0,
        0);

COMMIT;