CREATE TABLE LOCATION
(
    ID          INTEGER PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    IMAGE_URL   VARCHAR(255),
    SEASON_ID   INTEGER,
    REGION_ID   INTEGER
);

COMMIT;